name: Setup
description: Common setup steps for all jobs
runs:
  using: composite
  steps:
    - uses: asdf-vm/actions/install@v3
    - uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          node_modules
        key: deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: deps-${{ runner.os }}-
    - run: pnpm install
      shell: bash
